
name: Auto Comment
description: Automatically comment on issues when they are opened
run-name: Auto Comment on Issues
# comment: | https://github.com/marketplace/actions/auto-comment
on: [issues]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
        issues: write
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpenedReactions: 'eyes'
          issuesOpenedComment: |
            ðŸ‘‹ @{{ author }}
            Thank you for raising an issue on **Project ScEntra**.
            We appreciate your contribution and will review it as soon as possible.
            
            If you have any additional information or context to provide, please feel free to add it in the comments.
            
            We are here to help!
